### ISSUE TITLE
Restrict direct access to media directories

### ISSUE THREAD

**Issue by Philipinho** [FSTube/FSTube#1]
If one goes to the demo site (https://www.freespeechtube.org/mp4/j), one can view all the videos uploaded on the server.
I suggest you restrict direct access to directories. An .htaccess rule should solve this.

**Comment by EndeavourAccuracy** [comment]
Hi, thank you for the feedback. A recent move to another host appears to have solved this issue. I will therefore close it.

This comment I will end with a more general remark about the software. It disallows direct downloads of MP4 files with an .htaccess rule, and does not support hidden or private content, therefore visitors browsing uploaded content shouldn't be a (security) issue.
